sap.ui.define([
	"sap/ui/model/json/JSONModel",
	"sap/ui/Device"
], function (JSONModel, Device) {
	"use strict";

	return {

		createDeviceModel: function () {
			var oModel = new JSONModel(Device);
			oModel.setDefaultBindingMode("OneWay");
			return oModel;
		},
		oDataGeneralModel : function () {
               var oModel={
                     "filter": {}
               };
               return oModel;
            },
        oDataGeneralGetModel : function () {
            var oModel={
              "oDataVoucher":[],
           };
           return oModel;
        },

        JsonUserLoged: function () {
            var oModel = {
                "schemas":[
                   "urn:ietf:params:scim:api:messages:2.0:ListResponse"
                ],
                "totalResults":1,
                "itemsPerPage":100,
                "Resources":[
                   {
                      "id":"P000004",
                      "userUuid":"5dc2c547-b645-4068-afca-9a53ccc98f34",
                      "userName":"KASESTEFO",
                      "displayName":"",
                      "userType":"employee",
                      "sourceSystem":"0",
                      "passwordStatus":"enabled",
                      "mailVerified":"TRUE",
                      "passwordPolicy":"https://accounts.sap.com/policy/passwords/sap/enterprise/1.0",
                      "passwordFailedLoginAttempts":"0",
                      "passwordLoginTime":"2022-11-13T14:33:39Z",
                      "loginTime":"2022-11-13T02:52:12Z",
                      "passwordSetTime":"2022-11-07T19:13:09Z",
                      "schemas":[
                         "urn:ietf:params:scim:schemas:core:2.0:User",
                         "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User",
                         "urn:sap:cloud:scim:schemas:extension:custom:2.0:User"
                      ],
                      "active":true,
                      "meta":{
                         "location":"https://aijy7d89l.accounts.ondemand.com/service/scim/Users/P000004",
                         "resourceType":"User",
                         "version":"1.0",
                         "created":"2022-11-07T19:11:20Z",
                         "lastModified":"2022-11-13T19:23:52Z"
                      },
                      "emails":[
                         {
                            "value":"liderdeproyecto1@omniasolution.com",
                            "primary":true
                         }
                      ],
                      "name":{
                         "givenName":"Kassiel",
                         "familyName":"Estefo"
                      },
                      "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User":{
                         
                      },
                      "urn:sap:cloud:scim:schemas:extension:custom:2.0:User":{
                         "attributes":[
                            {
                               "name":"customAttribute1",
                               "value":"20605432183"
                            }
                         ]
                      }
                   }
                ],
                "oDataAditional":[
                   {
                      "Lifnr":"4000016026",
                      "Name":"PRODIMIN S.A.C.",
                      "Stcd1":"20605432183",
                      "Zdireccion":"LA ENCALADA  NRO. 1388  INT. 903 URBANIZACION LIMA POLO HUNT   Lima",
                      "Smtp_addr":"judith.matta@prodimin.pe"
                    }
                 ]
             }
            return oModel;
        },
        JsonGetHana: function(){
           var oModel={
              "oAuditResponse":{
                 "sIdTransaction":"20230506234849398219217",
                 "iCode":1,"sMessage":"OK"
              },
              "oResults":{
                 "oData":{
                    //correo estandar
                    "oMail":{
                       "iCode":1,
                       "sMessage":"OK",
                       "oData":[
                          {
                             "ID_ENTREGA_PROVEEDOR":"61",
                             "MODULO":"MM",
                             "APLICATIVO":
                             "SOLICITAR_CITA",
                             "FUNCION":"CORREO_CAMBIO_CONDICION",
                             "SOCIEDAD":"",
                             "CENTRO":"",
                             "CONTADOR":"",
                             "NUMERO_ENTREGA":"",
                             "DESDE":"",
                             "HASTA":"",
                             "DESCRIPCION":"KESTEFO@BUENAVENTURA.PE"
                          },
                          {
                             "ID_ENTREGA_PROVEEDOR":"82",
                             "MODULO":"MM",
                             "APLICATIVO":"SOLICITAR_CITA",
                             "FUNCION":"CORREO_CAMBIO_CONDICION",
                             "SOCIEDAD":"",
                             "CENTRO":"",
                             "CONTADOR":"",
                             "NUMERO_ENTREGA":"",
                             "DESDE":"",
                             "HASTA":"",
                             "DESCRIPCION":
                             "JAVIER.MUNOZ@BUENAVENTURA.PE"
                          },
                          {
                             "ID_ENTREGA_PROVEEDOR":"83",
                             "MODULO":"MM",
                             "APLICATIVO":
                             "SOLICITAR_CITA",
                             "FUNCION":"CORREO_CAMBIO_CONDICION",
                             "SOCIEDAD":"",
                             "CENTRO":"",
                             "CONTADOR":"",
                             "NUMERO_ENTREGA":"",
                             "DESDE":"",
                             "HASTA":"",
                             "DESCRIPCION":"JHONATAN.RAYMONDI@BUENAVENTURA.PE"
                          },
                          {
                             "ID_ENTREGA_PROVEEDOR":"81",
                             "MODULO":"MM",
                             "APLICATIVO":"SOLICITAR_CITA",
                             "FUNCION":"CORREO_CAMBIO_CONDICION",
                             "SOCIEDAD":"",
                             "CENTRO":"",
                             "CONTADOR":"",
                             "NUMERO_ENTREGA":"",
                             "DESDE":"",
                             "HASTA":"",
                             "DESCRIPCION":"YURI.SALAZAR@BUENAVENTURA.PE"
                          }
                       ],
                       "query":"SELECT * FROM \"IPROVIDER\".\"ENTREGA_PROVEEDOR\" WHERE 1 = 1  and \"MODULO\" = ? and \"APLICATIVO\" = ? and \"FUNCION\" = ? ",
                       "aParam":[
                          "SELECT * FROM \"IPROVIDER\".\"ENTREGA_PROVEEDOR\" WHERE 1 = 1  and \"MODULO\" = ? and \"APLICATIVO\" = ? and \"FUNCION\" = ? ","MM","SOLICITAR_CITA","CORREO_CAMBIO_CONDICION"
                       ]
                    },
                    //horario estandar
                    "oHolidays":{
                       "iCode":1,
                       "sMessage":"OK",
                       "oData":[
                          {
                             "ID_ENTREGA_PROVEEDOR":"46",
                             "MODULO":"MM",
                             "APLICATIVO":"SOLICITAR_CITA",
                             "FUNCION":"DIAS_FERIADOS",
                             "SOCIEDAD":"",
                             "CENTRO":"",
                             "CONTADOR":"",
                             "NUMERO_ENTREGA":"",
                             "DESDE":"",
                             "HASTA":"",
                             "DESCRIPCION":"29.07"
                          },
                          {
                             "ID_ENTREGA_PROVEEDOR":"47",
                             "MODULO":"MM",
                             "APLICATIVO":"SOLICITAR_CITA",
                             "FUNCION":"DIAS_FERIADOS",
                             "SOCIEDAD":"",
                             "CENTRO":"",
                             "CONTADOR":"",
                             "NUMERO_ENTREGA":"",
                             "DESDE":"",
                             "HASTA":"",
                             "DESCRIPCION":"01.01"
                          },
                          {
                             "ID_ENTREGA_PROVEEDOR":"48",
                             "MODULO":"MM",
                             "APLICATIVO":"SOLICITAR_CITA",
                             "FUNCION":"DIAS_FERIADOS",
                             "SOCIEDAD":"",
                             "CENTRO":"",
                             "CONTADOR":"",
                             "NUMERO_ENTREGA":"",
                             "DESDE":"",
                             "HASTA":"",
                             "DESCRIPCION":"06.04"
                          },
                          {
                             "ID_ENTREGA_PROVEEDOR":"49",
                             "MODULO":"MM",
                             "APLICATIVO":"SOLICITAR_CITA",
                             "FUNCION":"DIAS_FERIADOS",
                             "SOCIEDAD":"",
                             "CENTRO":"",
                             "CONTADOR":"",
                             "NUMERO_ENTREGA":"",
                             "DESDE":"",
                             "HASTA":"",
                             "DESCRIPCION":"07.04"
                          },
                          {
                             "ID_ENTREGA_PROVEEDOR":"50",
                             "MODULO":"MM",
                             "APLICATIVO":"SOLICITAR_CITA",
                             "FUNCION":"DIAS_FERIADOS",
                             "SOCIEDAD":"",
                             "CENTRO":"",
                             "CONTADOR":"",
                             "NUMERO_ENTREGA":"",
                             "DESDE":"",
                             "HASTA":"",
                             "DESCRIPCION":"01.05"
                          },
                          {
                             "ID_ENTREGA_PROVEEDOR":"51",
                             "MODULO":"MM",
                             "APLICATIVO":"SOLICITAR_CITA",
                             "FUNCION":"DIAS_FERIADOS",
                             "SOCIEDAD":"",
                             "CENTRO":"",
                             "CONTADOR":"",
                             "NUMERO_ENTREGA":"",
                             "DESDE":"",
                             "HASTA":"",
                             "DESCRIPCION":"29.06"
                          },
                          {
                             "ID_ENTREGA_PROVEEDOR":"52",
                             "MODULO":"MM",
                             "APLICATIVO":"SOLICITAR_CITA",
                             "FUNCION":"DIAS_FERIADOS",
                             "SOCIEDAD":"",
                             "CENTRO":"",
                             "CONTADOR":"",
                             "NUMERO_ENTREGA":"",
                             "DESDE":"",
                             "HASTA":"",
                             "DESCRIPCION":"28.07"
                          },
                          {
                             "ID_ENTREGA_PROVEEDOR":"53",
                             "MODULO":"MM",
                             "APLICATIVO":"SOLICITAR_CITA",
                             "FUNCION":"DIAS_FERIADOS",
                             "SOCIEDAD":"",
                             "CENTRO":"",
                             "CONTADOR":"",
                             "NUMERO_ENTREGA":"",
                             "DESDE":"",
                             "HASTA":"",
                             "DESCRIPCION":"29.07"
                          },
                          {
                             "ID_ENTREGA_PROVEEDOR":"54",
                             "MODULO":"MM",
                             "APLICATIVO":"SOLICITAR_CITA",
                             "FUNCION":"DIAS_FERIADOS",
                             "SOCIEDAD":"",
                             "CENTRO":"",
                             "CONTADOR":"",
                             "NUMERO_ENTREGA":"",
                             "DESDE":"",
                             "HASTA":"",
                             "DESCRIPCION":"30.08"
                          },
                          {
                             "ID_ENTREGA_PROVEEDOR":"55",
                             "MODULO":"MM",
                             "APLICATIVO":"SOLICITAR_CITA",
                             "FUNCION":"DIAS_FERIADOS",
                             "SOCIEDAD":"",
                             "CENTRO":"",
                             "CONTADOR":"",
                             "NUMERO_ENTREGA":"",
                             "DESDE":"",
                             "HASTA":"",
                             "DESCRIPCION":"08.10"
                          },
                          {
                             "ID_ENTREGA_PROVEEDOR":"56",
                             "MODULO":"MM",
                             "APLICATIVO":"SOLICITAR_CITA",
                             "FUNCION":"DIAS_FERIADOS",
                             "SOCIEDAD":"",
                             "CENTRO":"",
                             "CONTADOR":"",
                             "NUMERO_ENTREGA":"",
                             "DESDE":"",
                             "HASTA":"",
                             "DESCRIPCION":"01.11"
                          },
                          {
                             "ID_ENTREGA_PROVEEDOR":"57",
                             "MODULO":"MM",
                             "APLICATIVO":"SOLICITAR_CITA",
                             "FUNCION":"DIAS_FERIADOS",
                             "SOCIEDAD":"",
                             "CENTRO":"",
                             "CONTADOR":"",
                             "NUMERO_ENTREGA":"",
                             "DESDE":"",
                             "HASTA":"",
                             "DESCRIPCION":"08.12"
                          },
                          {
                             "ID_ENTREGA_PROVEEDOR":"58",
                             "MODULO":"MM",
                             "APLICATIVO":"SOLICITAR_CITA",
                             "FUNCION":"DIAS_FERIADOS",
                             "SOCIEDAD":"",
                             "CENTRO":"",
                             "CONTADOR":"",
                             "NUMERO_ENTREGA":"",
                             "DESDE":"",
                             "HASTA":"",
                             "DESCRIPCION":"25.12"
                          },
                          {
                             "ID_ENTREGA_PROVEEDOR":"189",
                             "MODULO":"MM",
                             "APLICATIVO":"SOLICITAR_CITA",
                             "FUNCION":"DIAS_FERIADOS",
                             "SOCIEDAD":"",
                             "CENTRO":"",
                             "CONTADOR":"",
                             "NUMERO_ENTREGA":"",
                             "DESDE":"",
                             "HASTA":"",
                             "DESCRIPCION":"24.12"
                          },
                          {
                             "ID_ENTREGA_PROVEEDOR":"190",
                             "MODULO":"MM",
                             "APLICATIVO":"SOLICITAR_CITA",
                             "FUNCION":"DIAS_FERIADOS",
                             "SOCIEDAD":"",
                             "CENTRO":"",
                             "CONTADOR":"",
                             "NUMERO_ENTREGA":"",
                             "DESDE":"",
                             "HASTA":"",
                             "DESCRIPCION":"31.12"
                          },
                          {
                             "ID_ENTREGA_PROVEEDOR":"198",
                             "MODULO":"MM",
                             "APLICATIVO":"SOLICITAR_CITA",
                             "FUNCION":"DIAS_FERIADOS",
                             "SOCIEDAD":"",
                             "CENTRO":"",
                             "CONTADOR":"",
                             "NUMERO_ENTREGA":"",
                             "DESDE":"",
                             "HASTA":"",
                             "DESCRIPCION":"16.12"
                          },
                          {
                             "ID_ENTREGA_PROVEEDOR":"196",
                             "MODULO":"MM",
                             "APLICATIVO":"SOLICITAR_CITA",
                             "FUNCION":"DIAS_FERIADOS",
                             "SOCIEDAD":"",
                             "CENTRO":"",
                             "CONTADOR":"",
                             "NUMERO_ENTREGA":"",
                             "DESDE":"",
                             "HASTA":"",
                             "DESCRIPCION":"09.12"
                          },
                          {
                             "ID_ENTREGA_PROVEEDOR":"197",
                             "MODULO":"MM",
                             "APLICATIVO":"SOLICITAR_CITA",
                             "FUNCION":"DIAS_FERIADOS",
                             "SOCIEDAD":"",
                             "CENTRO":"",
                             "CONTADOR":"",
                             "NUMERO_ENTREGA":"",
                             "DESDE":"",
                             "HASTA":"",
                             "DESCRIPCION":"15.12"
                          }
                       ],
                       "query":"SELECT * FROM \"IPROVIDER\".\"ENTREGA_PROVEEDOR\" WHERE 1 = 1  and \"MODULO\" = ? and \"APLICATIVO\" = ? and \"FUNCION\" = ? ",
                       "aParam":[
                          "SELECT * FROM \"IPROVIDER\".\"ENTREGA_PROVEEDOR\" WHERE 1 = 1  and \"MODULO\" = ? and \"APLICATIVO\" = ? and \"FUNCION\" = ? ",
                          "MM",
                          "SOLICITAR_CITA",
                          "DIAS_FERIADOS"
                       ]
                    },
                    //feriados
                    "oToleranceSchule":{
                       "iCode":1,
                       "sMessage":"OK",
                       "oData":[
                          {
                             "ID_ENTREGA_PROVEEDOR":"37",
                             "MODULO":"MM",
                             "APLICATIVO":"SOLICITAR_CITA",
                             "FUNCION":"HORAS_TOLERANCIA",
                             "SOCIEDAD":"",
                             "CENTRO":"",
                             "CONTADOR":"1",
                             "NUMERO_ENTREGA":"",
                             "DESDE":"",
                             "HASTA":"",
                             "DESCRIPCION":"HORAS DE TOLERANCIA PARA ELIMINACION DE ENTREGAS"
                          }
                       ],
                       "query":"SELECT * FROM \"IPROVIDER\".\"ENTREGA_PROVEEDOR\" WHERE 1 = 1  and \"MODULO\" = ? and \"APLICATIVO\" = ? and \"FUNCION\" = ? ",
                       "aParam":[
                          "SELECT * FROM \"IPROVIDER\".\"ENTREGA_PROVEEDOR\" WHERE 1 = 1  and \"MODULO\" = ? and \"APLICATIVO\" = ? and \"FUNCION\" = ? ",
                          "MM",
                          "SOLICITAR_CITA",
                          "HORAS_TOLERANCIA"
                       ]
                    },
                    //hora trabajada
                    "oWorkingHour":{
                       "iCode":1,
                       "sMessage":"OK",
                       "oData":[
                          {
                             "ID_ENTREGA_PROVEEDOR":"36",
                             "MODULO":"MM",
                             "APLICATIVO":"SOLICITAR_CITA",
                             "FUNCION":"HORA_TRABAJADAS",
                             "SOCIEDAD":"",
                             "CENTRO":"",
                             "CONTADOR":"1",
                             "NUMERO_ENTREGA":"",
                             "DESDE":"",
                             "HASTA":"",
                             "DESCRIPCION":"HORAS DE TRABAJO PARA LA PLANIFICACION"
                          }
                       ],
                       "query":"SELECT * FROM \"IPROVIDER\".\"ENTREGA_PROVEEDOR\" WHERE 1 = 1  and \"MODULO\" = ? and \"APLICATIVO\" = ? and \"FUNCION\" = ? ",
                       "aParam":[
                          "SELECT * FROM \"IPROVIDER\".\"ENTREGA_PROVEEDOR\" WHERE 1 = 1  and \"MODULO\" = ? and \"APLICATIVO\" = ? and \"FUNCION\" = ? ",
                          "MM",
                          "SOLICITAR_CITA",
                          "HORA_TRABAJADAS"
                       ]
                    },
                    //Centro
                    "oCenter":{
                       "iCode":1,
                       "sMessage":"OK",
                       "oData":[
                          {
                             "ID_ENTREGA_PROVEEDOR":"6",
                             "MODULO":"MM",
                             "APLICATIVO":"SOLICITAR_CITA",
                             "FUNCION":"CENTRO",
                             "CENTRO":"1000"
                          },
                          {
                             "ID_ENTREGA_PROVEEDOR":"187",
                             "MODULO":"MM",
                             "APLICATIVO":"SOLICITAR_CITA",
                             "FUNCION":"CENTRO",
                             "CENTRO":"1097"
                          },
                          {
                             "ID_ENTREGA_PROVEEDOR":"7",
                             "MODULO":"MM",
                             "APLICATIVO":"SOLICITAR_CITA",
                             "FUNCION":"CENTRO",
                             "CENTRO":"1100"
                          },
                          {
                             "ID_ENTREGA_PROVEEDOR":"8",
                             "MODULO":"MM",
                             "APLICATIVO":"SOLICITAR_CITA",
                             "FUNCION":"CENTRO",
                             "CENTRO":"1200"
                          },
                          {
                             "ID_ENTREGA_PROVEEDOR":"10",
                             "MODULO":"MM",
                             "APLICATIVO":"SOLICITAR_CITA",
                             "FUNCION":"CENTRO",
                             "CENTRO":"1300"
                          },
                          {
                             "ID_ENTREGA_PROVEEDOR":"9",
                             "MODULO":"MM",
                             "APLICATIVO":"SOLICITAR_CITA",
                             "FUNCION":"CENTRO",
                             "CENTRO":"1400"
                          },
                          {
                             "ID_ENTREGA_PROVEEDOR":"11",
                             "MODULO":"MM",
                             "APLICATIVO":"SOLICITAR_CITA",
                             "FUNCION":"CENTRO",
                             "CENTRO":"1500"
                          },
                          {
                             "ID_ENTREGA_PROVEEDOR":"12",
                             "MODULO":"MM",
                             "APLICATIVO":"SOLICITAR_CITA",
                             "FUNCION":"CENTRO",
                             "CENTRO":"1600"
                          },
                          {
                             "ID_ENTREGA_PROVEEDOR":"13",
                             "MODULO":"MM",
                             "APLICATIVO":"SOLICITAR_CITA",
                             "FUNCION":"CENTRO",
                             "CENTRO":"1700"
                          },
                          {
                             "ID_ENTREGA_PROVEEDOR":"14",
                             "MODULO":"MM",
                             "APLICATIVO":"SOLICITAR_CITA",
                             "FUNCION":"CENTRO",
                             "CENTRO":"1800"
                          },
                          {
                             "ID_ENTREGA_PROVEEDOR":"15",
                             "MODULO":"MM",
                             "APLICATIVO":"SOLICITAR_CITA",
                             "FUNCION":"CENTRO",
                             "CENTRO":"1900"
                          },
                          {
                             "ID_ENTREGA_PROVEEDOR":"16",
                             "MODULO":"MM",
                             "APLICATIVO":"SOLICITAR_CITA",
                             "FUNCION":"CENTRO",
                             "CENTRO":"2000"
                          },
                          {
                             "ID_ENTREGA_PROVEEDOR":"17",
                             "MODULO":"MM",
                             "APLICATIVO":"SOLICITAR_CITA",
                             "FUNCION":"CENTRO",
                             "CENTRO":"2100"
                          },
                          {
                             "ID_ENTREGA_PROVEEDOR":"18",
                             "MODULO":"MM",
                             "APLICATIVO":"SOLICITAR_CITA",
                             "FUNCION":"CENTRO",
                             "CENTRO":"7000"
                          },
                          {
                             "ID_ENTREGA_PROVEEDOR":"19",
                             "MODULO":"MM",
                             "APLICATIVO":"SOLICITAR_CITA",
                             "FUNCION":"CENTRO",
                             "CENTRO":"7100"
                          },
                          {
                             "ID_ENTREGA_PROVEEDOR":"20",
                             "MODULO":"MM",
                             "APLICATIVO":"SOLICITAR_CITA",
                             "FUNCION":"CENTRO",
                             "CENTRO":"8000"
                          },
                          {
                             "ID_ENTREGA_PROVEEDOR":"21",
                             "MODULO":"MM",
                             "APLICATIVO":"SOLICITAR_CITA",
                             "FUNCION":"CENTRO",
                             "CENTRO":"8100"
                          },
                          {
                             "ID_ENTREGA_PROVEEDOR":"22",
                             "MODULO":"MM",
                             "APLICATIVO":"SOLICITAR_CITA",
                             "FUNCION":"CENTRO",
                             "CENTRO":"8200"
                          }
                       ],
                       "query":"SELECT * FROM \"IPROVIDER\".\"ENTREGA_PROVEEDOR\" WHERE 1 = 1  and \"MODULO\" = ? and \"APLICATIVO\" = ? and \"FUNCION\" = ? ",
                       "aParam":[
                          "SELECT * FROM \"IPROVIDER\".\"ENTREGA_PROVEEDOR\" WHERE 1 = 1  and \"MODULO\" = ? and \"APLICATIVO\" = ? and \"FUNCION\" = ? ",
                          "MM",
                          "SOLICITAR_CITA",
                          "CENTRO"
                       ]
                    },
                    //Condicion de entrega
                    "oCondAppointment":{
                       "iCode":1,
                       "sMessage":"OK",
                       "oData":[
                          {}
                       ],
                       "query":"SELECT * FROM \"IPROVIDER\".\"ENTREGA_PROVEEDOR\" WHERE 1 = 1  and \"MODULO\" = ? and \"APLICATIVO\" = ? and \"FUNCION\" = ? ",
                       "aParam":[
                          "SELECT * FROM \"IPROVIDER\".\"ENTREGA_PROVEEDOR\" WHERE 1 = 1  and \"MODULO\" = ? and \"APLICATIVO\" = ? and \"FUNCION\" = ? ",
                          "MM",
                          "SOLICITAR_CITA",
                          "COND_ENTREGA"
                       ]
                    },
                    //unidades de embalaje
                    "oPackingUnits":{
                       "iCode":1,
                       "sMessage":"OK",
                       "oData":[
                          {
                             "ID_ENTREGA_PROVEEDOR":"45",
                             "MODULO":"MM",
                             "APLICATIVO":"SOLICITAR_CITA",
                             "FUNCION":"UNIDAD_EMBALAJE",
                             "SOCIEDAD":"",
                             "CENTRO":"",
                             "CONTADOR":"",
                             "NUMERO_ENTREGA":"",
                             "DESDE":"",
                             "HASTA":"",
                             "DESCRIPCION":"KG"
                          }
                       ],
                       "query":"SELECT * FROM \"IPROVIDER\".\"ENTREGA_PROVEEDOR\" WHERE 1 = 1  and \"MODULO\" = ? and \"APLICATIVO\" = ? and \"FUNCION\" = ? ",
                       "aParam":[
                          "SELECT * FROM \"IPROVIDER\".\"ENTREGA_PROVEEDOR\" WHERE 1 = 1  and \"MODULO\" = ? and \"APLICATIVO\" = ? and \"FUNCION\" = ? ",
                          "MM",
                          "SOLICITAR_CITA",
                          "UNIDAD_EMBALAJE"
                       ]
                    }
                 },
                 "iCode":1,
                 "sMessage":"OK"
              }
           };
           return oModel;
        },
        JsonGetERP: function(){
           var oModel={};
           return oModel;
        },

	};
});